apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-health-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-health-api
  template:
    metadata:
      labels:
        app: network-health-api
    spec:

      # ----------------------
      # INIT CONTAINER
      # ----------------------
      initContainers:
        - name: init-db
          image: network-health-api-api:latest
          imagePullPolicy: IfNotPresent
          command:
            - python
            - -m
            - app.scripts.init_db
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: DATABASE_URL

      # ----------------------
      # MAIN CONTAINER
      # ----------------------
      containers:
        - name: api
          image: network-health-api-api:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: DATABASE_URL

            - name: ENV
              value: "prod"

          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

